### ISSUE TITLE
Numpy dependency broken

### ISSUE THREAD

**Issue by gabrielpgagne** [LibEMG/libemg#40]
From `requirements.txt`, numpy is not pinned.

On June 16th 2024, numpy 2.0 was released on PyPI, introducing a few breaking changes.

On a brand new Python3.12 installation on Win11, installing LibEMG pulled in numpy 2.0. Some LibEMG dependencies seem to break.

```python

$ python -c "import libemg"

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\GAGAG158\Documents\libemgtest\test.py", line 1, in <module>
    from libemg.data_handler import OnlineDataHandler
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\libemg\__init__.py", line 1, in <module>
    from libemg import feature_extractor
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\libemg\feature_extractor.py", line 9, in <module>
    from librosa import lpc
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\lazy_loader\__init__.py", line 83, in __getattr__
    attr = getattr(submod, name)
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\lazy_loader\__init__.py", line 82, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\GAGAG158\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\librosa\core\audio.py", line 15, in <module>
    import soxr
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\soxr\__init__.py", line 10, in <module>
    from . import cysoxr
Traceback (most recent call last):
  File "c:\Users\GAGAG158\Documents\libemgtest\test.py", line 1, in <module>
    from libemg.data_handler import OnlineDataHandler
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\libemg\__init__.py", line 1, in <module>
    from libemg import feature_extractor
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\libemg\feature_extractor.py", line 9, in <module>
    from librosa import lpc
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\lazy_loader\__init__.py", line 83, in __getattr__
    attr = getattr(submod, name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\lazy_loader\__init__.py", line 82, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GAGAG158\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\librosa\core\audio.py", line 15, in <module>
    import soxr
  File "C:\Users\GAGAG158\Documents\libemgtest\.venv\Lib\site-packages\soxr\__init__.py", line 10, in <module>
    from . import cysoxr
  File "src\\soxr\\cysoxr.pyx", line 1, in init soxr.cysoxr
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

Proposed fix is simply to pin numpy<2.0

**Comment by ECEEvanCampbell** [comment]
Added version specification to requirements.txt (numpy==1.24.6)
